site: J3ZZ / Jérôme Li-Thiao-Té 's Personal Site

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  projects:
    output: true
    permalink: /project/:slug
  photographs:
    output: true
    permalink: /photo/:slug
  arts:
    output: true
    permalink: /arts/:slug


defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  -
    scope:
      path: ""
      type: "photographs"
    values:
      layout: "project"
  -
    scope:
      path: ""
      type: "arts"
    values:
      layout: "project"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-analytics
  - jekyll-scholar

google_analytics: #TODO UA-167416614-1

paginate: 6
paginate_path: "/blog/page:num/"

scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  source: ./documents/publications/
  bibliography: bibliography.bib
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
